[project]
name = "linkedin-clone-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "alembic>=1.16.5",
    "fastapi>=0.128.8",
    "psycopg[binary]>=3.2.13",
    "pwdlib[argon2]>=0.2.1",
    "pyjwt>=2.15.1",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.54",
    "uvicorn[standard]>=0.39.0",
]

[project.scripts]
linkedin-clone-fastapi = "linkedin_clone_fastapi:main"

[build-system]
requires = ["uv_build>=0.12.24,<0.13.0"]
build-backend = "uv_build"
